-- MySQL Script generated by MySQL Workbench
-- Mon Oct  1 21:09:10 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `ch.arexa.hesge.jdbc.bank.Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ch.arexa.hesge.jdbc.bank.Client` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NULL,
  PRIMARY KEY (`idClient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ch.arexa.hesge.jdbc.bank.Account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ch.arexa.hesge.jdbc.bank.Account` (
  `accountRef` VARCHAR(45) NOT NULL,
  `idClient` VARCHAR(45) NULL,
  `balance` DOUBLE NULL,
  PRIMARY KEY (`accountRef`)
  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ch.arexa.hesge.jdbc.bank.TransferOrder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ch.arexa.hesge.jdbc.bank.TransferOrder` (
  `idTransferOrder` INT NOT NULL,
  `accountRef1` VARCHAR(45) NOT NULL,
  `accountRef2` VARCHAR(45) NOT NULL,
  `amount` DOUBLE NULL,
  PRIMARY KEY (`idTransferOrder`)
  )
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO `bank`.`client` (`idClient`, `name`, `address`) VALUES ('1', 'Vincent', 'rue du Salve');
INSERT INTO `bank`.`client` (`idClient`, `name`, `address`) VALUES ('2', 'Lucie', 'rue du Fort');


INSERT INTO `bank`.`account` (`accountRef`, `idClient`, `balance`) VALUES ('A1', '1', '100');
INSERT INTO `bank`.`account` (`accountRef`, `idClient`, `balance`) VALUES ('A2', '1', '1000');
INSERT INTO `bank`.`account` (`accountRef`, `idClient`, `balance`) VALUES ('A3', '2', '500');
INSERT INTO `bank`.`account` (`accountRef`, `idClient`, `balance`) VALUES ('A4', '2', '500');


INSERT INTO `bank`.`transferorder` (`idTransferOrder`, `accountRef1`, `accountRef2`, `amount`) VALUES ('1', 'A1', 'A2', '50');
INSERT INTO `bank`.`transferorder` (`idTransferOrder`, `accountRef1`, `accountRef2`, `amount`) VALUES ('2', 'A3', 'A4', '2000');
INSERT INTO `bank`.`transferorder` (`idTransferOrder`, `accountRef1`, `accountRef2`, `amount`) VALUES ('3', 'A1', 'A3', '100');

